version: '3.7'

services:
  app:
    build: .
    depends_on:
      - redis-master
    command: /bin/bash -c "echo 'Waiting for redis to run..' && sleep 5 && python aquarium.py"
    volumes:
      - ./app:/usr/src/app/redis_app/
    links:
      - redis-sentinel
      - redis-sentinel2
      - redis-sentinel3
  
  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - 7843:7843
    depends_on:
      - redis-master
    volumes:
      - ./p3x-redis-ui-settings:/settings

  redis-master:
    image: redis:7.0.8-alpine
    volumes:
      - "./redis-data/.data:/data"
    ports:
      - "6379:6379"

  redis-slave:
    image: redis:7.0.8-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./redis-data/.data-slave:/data"

  # Instance 1
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - "26379:26379"

  # Instance 2
  redis-sentinel2:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - "26380:26379"
 
  # Instance 3
  redis-sentinel3:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - "26381:26379"

